
name: Java with Maven Goals

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Compile with Maven
      run: mvn compile
      continue-on-error: true

    - name: Display Maven Compilation Output
      if: ${{ failure() }}
      run: cat target/maven-compiler-plugin.log

    - name: Test with Maven
      run: mvn test

    - name: Package with Maven
      run: mvn package

    - name: Install with Maven
      run: mvn install

    - name: Clean with Maven
      run: mvn clean

    - name: Verify with Maven
      run: mvn verify
